language: ruby
rvm:
- 2.1.5
addons:
  postgresql: '9.3'
bundler_args: "--without production --path=~/.bundle"
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- gem install bundler bundle_cache
- bundle_cache_install
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database "test-postgres_test";' -U postgres
script:
- bundle exec rake db:migrate db:test:prepare db:seed
- bundle exec rake cucumber
- bundle exec rake spec
after_script:
- bundle_cache
env:
  global:
  - BUNDLE_ARCHIVE="bundle.tgz"
  - AWS_S3_BUCKET="cs61as-team"
  - RAILS_ENV=test
  - CODECLIMATE_REPO_TOKEN=2df9384e17b8b855376608fb9840f6127d410b0d7cfa2374962957c8f9d1b68a
  - secure: Szkst9NJvuIPKsvFLbuFHgIiBFfubpM/Fk5c/QktMAw0CQAyryDatD4f1YPP9K6rdKJU2exhOKEmfQc+B52nOfM6diXM36ifMzQkA3X6PiiBkLi3QzcWyzMnPvRLrIo7xDEczGuO1nilNPxyfGw8AcTJoBV43syMWJpg1m8waEM=
